### ISSUE TITLE
Test Case Review

### ISSUE THREAD

**Issue by RourkeDawson** [joshuanario/digits#4]
this test case: https://github.com/joshuanario/digits/blob/d391bf4b7f99bfce9b994f8104f9082715491da2/digits_test.go#L77-L92

`sigFigs` and `nonSigFigs` calculate as expected. The expected `strOut` is "77,190,000.00", with `precision` requested at the Millions. Is this actually expected, or should it be "77,000,000.00"?

if it is supposed to be as shown, then what is the intent with the first test case here: https://github.com/joshuanario/digits/blob/d391bf4b7f99bfce9b994f8104f9082715491da2/digits_test.go#L29-L44

Is exact precision expected in the integer part of the value, while the fractional part is rounded unless precision is specified in the tenths/hundredths?

This is a pretty critical distinction that isn't obvious from terminology alone, and should probably be clarified in the readme, if this is some non-standard implementation w/ regard to XBRL.

**Comment by RourkeDawson** [comment]
@joshuanario pinging you for review, as this clarification is a bit of a blocker. I can chat sometime tomorrow afternoon if needed.

**Comment by joshuanario** [comment]
Thanks for taking the time to understand and review the inner workings of `digits`.  Now that I'm reviewing this test case, this is not correct behavior for `digits`.  This test case should modified and updated.

https://github.com/joshuanario/digits/blob/d391bf4b7f99bfce9b994f8104f9082715491da2/digits_test.go#L29-L44

This test case should be updated with the following specifications:

```
 	stimulus: Stimulus{ 
 		precision:           digits.Oneth, 
 		value:               "0.99", 
 		groupSeparator:      ',', 
 		fractionalPrecision: digits.PreserveUpToHundredth, 
 	}, 
 	expectation: Expectation{ 
 		sigFigs:    "0.", 
 		nonSigFigs: "99", 
 		strOut:     "0.99", 
 		head:       "", 
 		core:       "0.",   //decimal points (or separators) should always be in core if the precisions is in the oneth place (this also holds true for EXACT precisions) and should not show up in tail for those specific conditions
 		tail:       "99", 
 	}, 

```

**Comment by RourkeDawson** [comment]
Pinned another test that I'm uncertain is correct or not.

this is the original stimulus:
https://github.com/joshuanario/digits/blob/c035e151ea77253aac2eeb5149beae8c9170d92a/digits_test.go#L89-L94

modified stimulus (same stimulus, updated format):
https://github.com/joshuanario/digits/blob/d9d2bd64032896cf3eed050a82ccf68041883cc5/digits_test.go#L221-L236

are decimal points intended to show up in core, if the defined precision is exact? why would the core have 1,038,807., but the sigFig have 1,038,807?
Just want to make sure this is the desired effect, or I should be generating a core with the . attached when precision is exact and the sigFig doesn't include trailing decimals.

**Comment by joshuanario** [comment]
For the case of Oneth, the decimal point should show up in core.

For the case of Exact, if the input string has no decimal point, then the last character in the string is assumed to be the oneth digits and the core should render the decimal point after this character.  However, if the decimal point is present, determine the resultant precision of the numeric expression, but this resultant precision should not go beyond the the bounds of the decimal digit preservation.
